cluster.name: kubernetes-logging

node.master: ${NODE_MASTER}
node.data: ${NODE_DATA}
node.name: ${HOSTNAME}

network.host: 0.0.0.0
transport.tcp.port: ${TRANSPORT_PORT}
http.port: ${HTTP_PORT}

cloud:
  kubernetes:
    service: ${SERVICE}
    namespace: ${KUBERNETES_NAMESPACE}

discovery.zen.hosts_provider: kubernetes

discovery.zen.minimum_master_nodes: 2

xpack.security.enabled: false

plugin.mandatory: discovery-kubernetes